// Generated by create-embed.go.sh

package fonts

import (
	_ "embed"
)

//go:embed playfairdisplay/PlayfairDisplay-VariableFont_wght.ttf
var PlayfairDisplay_VariableFont_wght_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-Bold.ttf
var PlayfairDisplay_Bold_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-SemiBold.ttf
var PlayfairDisplay_SemiBold_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-Medium.ttf
var PlayfairDisplay_Medium_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-BoldItalic.ttf
var PlayfairDisplay_BoldItalic_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-ExtraBoldItalic.ttf
var PlayfairDisplay_ExtraBoldItalic_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-Italic.ttf
var PlayfairDisplay_Italic_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-Regular.ttf
var PlayfairDisplay_Regular_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-Black.ttf
var PlayfairDisplay_Black_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-SemiBoldItalic.ttf
var PlayfairDisplay_SemiBoldItalic_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-MediumItalic.ttf
var PlayfairDisplay_MediumItalic_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-BlackItalic.ttf
var PlayfairDisplay_BlackItalic_ttf []byte

//go:embed playfairdisplay/static/PlayfairDisplay-ExtraBold.ttf
var PlayfairDisplay_ExtraBold_ttf []byte

//go:embed playfairdisplay/PlayfairDisplay-Italic-VariableFont_wght.ttf
var PlayfairDisplay_Italic_VariableFont_wght_ttf []byte

//go:embed indieflower/IndieFlower-Regular.ttf
var IndieFlower_Regular_ttf []byte

//go:embed patrickhand/PatrickHand-Regular.ttf
var PatrickHand_Regular_ttf []byte

//go:embed orbitron/static/Orbitron-Black.ttf
var Orbitron_Black_ttf []byte

//go:embed orbitron/static/Orbitron-Medium.ttf
var Orbitron_Medium_ttf []byte

//go:embed orbitron/static/Orbitron-ExtraBold.ttf
var Orbitron_ExtraBold_ttf []byte

//go:embed orbitron/static/Orbitron-Regular.ttf
var Orbitron_Regular_ttf []byte

//go:embed orbitron/static/Orbitron-SemiBold.ttf
var Orbitron_SemiBold_ttf []byte

//go:embed orbitron/static/Orbitron-Bold.ttf
var Orbitron_Bold_ttf []byte

//go:embed orbitron/Orbitron-VariableFont_wght.ttf
var Orbitron_VariableFont_wght_ttf []byte

//go:embed merriweather/Merriweather-Bold.ttf
var Merriweather_Bold_ttf []byte

//go:embed merriweather/Merriweather-Regular.ttf
var Merriweather_Regular_ttf []byte

//go:embed merriweather/Merriweather-Light.ttf
var Merriweather_Light_ttf []byte

//go:embed merriweather/Merriweather-BoldItalic.ttf
var Merriweather_BoldItalic_ttf []byte

//go:embed merriweather/Merriweather-BlackItalic.ttf
var Merriweather_BlackItalic_ttf []byte

//go:embed merriweather/Merriweather-Italic.ttf
var Merriweather_Italic_ttf []byte

//go:embed merriweather/Merriweather-Black.ttf
var Merriweather_Black_ttf []byte

//go:embed merriweather/Merriweather-LightItalic.ttf
var Merriweather_LightItalic_ttf []byte

//go:embed magicschool/MagicSchoolOne.ttf
var MagicSchoolOne_ttf []byte

//go:embed magicschool/MagicSchoolTwo.ttf
var MagicSchoolTwo_ttf []byte

//go:embed oswald/static/Oswald-Bold.ttf
var Oswald_Bold_ttf []byte

//go:embed oswald/static/Oswald-SemiBold.ttf
var Oswald_SemiBold_ttf []byte

//go:embed oswald/static/Oswald-Medium.ttf
var Oswald_Medium_ttf []byte

//go:embed oswald/static/Oswald-Regular.ttf
var Oswald_Regular_ttf []byte

//go:embed oswald/static/Oswald-ExtraLight.ttf
var Oswald_ExtraLight_ttf []byte

//go:embed oswald/static/Oswald-Light.ttf
var Oswald_Light_ttf []byte

//go:embed oswald/Oswald-VariableFont_wght.ttf
var Oswald_VariableFont_wght_ttf []byte

//go:embed exo2/Exo2-VariableFont_wght.ttf
var Exo2_VariableFont_wght_ttf []byte

//go:embed exo2/Exo2-Italic-VariableFont_wght.ttf
var Exo2_Italic_VariableFont_wght_ttf []byte

//go:embed exo2/static/Exo2-Thin.ttf
var Exo2_Thin_ttf []byte

//go:embed exo2/static/Exo2-ExtraBold.ttf
var Exo2_ExtraBold_ttf []byte

//go:embed exo2/static/Exo2-Italic.ttf
var Exo2_Italic_ttf []byte

//go:embed exo2/static/Exo2-ExtraLight.ttf
var Exo2_ExtraLight_ttf []byte

//go:embed exo2/static/Exo2-ThinItalic.ttf
var Exo2_ThinItalic_ttf []byte

//go:embed exo2/static/Exo2-BoldItalic.ttf
var Exo2_BoldItalic_ttf []byte

//go:embed exo2/static/Exo2-Regular.ttf
var Exo2_Regular_ttf []byte

//go:embed exo2/static/Exo2-Bold.ttf
var Exo2_Bold_ttf []byte

//go:embed exo2/static/Exo2-Light.ttf
var Exo2_Light_ttf []byte

//go:embed exo2/static/Exo2-ExtraBoldItalic.ttf
var Exo2_ExtraBoldItalic_ttf []byte

//go:embed exo2/static/Exo2-BlackItalic.ttf
var Exo2_BlackItalic_ttf []byte

//go:embed exo2/static/Exo2-Black.ttf
var Exo2_Black_ttf []byte

//go:embed exo2/static/Exo2-ExtraLightItalic.ttf
var Exo2_ExtraLightItalic_ttf []byte

//go:embed exo2/static/Exo2-LightItalic.ttf
var Exo2_LightItalic_ttf []byte

//go:embed exo2/static/Exo2-SemiBold.ttf
var Exo2_SemiBold_ttf []byte

//go:embed exo2/static/Exo2-Medium.ttf
var Exo2_Medium_ttf []byte

//go:embed exo2/static/Exo2-MediumItalic.ttf
var Exo2_MediumItalic_ttf []byte

//go:embed exo2/static/Exo2-SemiBoldItalic.ttf
var Exo2_SemiBoldItalic_ttf []byte

//go:embed montserrat/Montserrat-VariableFont_wght.ttf
var Montserrat_VariableFont_wght_ttf []byte

//go:embed montserrat/Montserrat-Italic-VariableFont_wght.ttf
var Montserrat_Italic_VariableFont_wght_ttf []byte

//go:embed montserrat/static/Montserrat-LightItalic.ttf
var Montserrat_LightItalic_ttf []byte

//go:embed montserrat/static/Montserrat-Medium.ttf
var Montserrat_Medium_ttf []byte

//go:embed montserrat/static/Montserrat-BoldItalic.ttf
var Montserrat_BoldItalic_ttf []byte

//go:embed montserrat/static/Montserrat-Light.ttf
var Montserrat_Light_ttf []byte

//go:embed montserrat/static/Montserrat-ThinItalic.ttf
var Montserrat_ThinItalic_ttf []byte

//go:embed montserrat/static/Montserrat-ExtraLight.ttf
var Montserrat_ExtraLight_ttf []byte

//go:embed montserrat/static/Montserrat-Thin.ttf
var Montserrat_Thin_ttf []byte

//go:embed montserrat/static/Montserrat-Bold.ttf
var Montserrat_Bold_ttf []byte

//go:embed montserrat/static/Montserrat-MediumItalic.ttf
var Montserrat_MediumItalic_ttf []byte

//go:embed montserrat/static/Montserrat-BlackItalic.ttf
var Montserrat_BlackItalic_ttf []byte

//go:embed montserrat/static/Montserrat-SemiBold.ttf
var Montserrat_SemiBold_ttf []byte

//go:embed montserrat/static/Montserrat-ExtraLightItalic.ttf
var Montserrat_ExtraLightItalic_ttf []byte

//go:embed montserrat/static/Montserrat-ExtraBold.ttf
var Montserrat_ExtraBold_ttf []byte

//go:embed montserrat/static/Montserrat-Black.ttf
var Montserrat_Black_ttf []byte

//go:embed montserrat/static/Montserrat-Regular.ttf
var Montserrat_Regular_ttf []byte

//go:embed montserrat/static/Montserrat-Italic.ttf
var Montserrat_Italic_ttf []byte

//go:embed montserrat/static/Montserrat-SemiBoldItalic.ttf
var Montserrat_SemiBoldItalic_ttf []byte

//go:embed montserrat/static/Montserrat-ExtraBoldItalic.ttf
var Montserrat_ExtraBoldItalic_ttf []byte

//go:embed pixeloperator/PixelOperatorSC.ttf
var PixelOperatorSC_ttf []byte

//go:embed pixeloperator/PixelOperatorMono8.ttf
var PixelOperatorMono8_ttf []byte

//go:embed pixeloperator/PixelOperator8.ttf
var PixelOperator8_ttf []byte

//go:embed pixeloperator/PixelOperatorMono-Bold.ttf
var PixelOperatorMono_Bold_ttf []byte

//go:embed pixeloperator/PixelOperator-Bold.ttf
var PixelOperator_Bold_ttf []byte

//go:embed pixeloperator/PixelOperator8-Bold.ttf
var PixelOperator8_Bold_ttf []byte

//go:embed pixeloperator/PixelOperatorHBSC.ttf
var PixelOperatorHBSC_ttf []byte

//go:embed pixeloperator/PixelOperator.ttf
var PixelOperator_ttf []byte

//go:embed pixeloperator/PixelOperatorHB8.ttf
var PixelOperatorHB8_ttf []byte

//go:embed pixeloperator/PixelOperatorMonoHB.ttf
var PixelOperatorMonoHB_ttf []byte

//go:embed pixeloperator/PixelOperatorMono.ttf
var PixelOperatorMono_ttf []byte

//go:embed pixeloperator/PixelOperatorHB.ttf
var PixelOperatorHB_ttf []byte

//go:embed pixeloperator/PixelOperatorMonoHB8.ttf
var PixelOperatorMonoHB8_ttf []byte

//go:embed pixeloperator/PixelOperatorSC-Bold.ttf
var PixelOperatorSC_Bold_ttf []byte

//go:embed pixeloperator/PixelOperatorMono8-Bold.ttf
var PixelOperatorMono8_Bold_ttf []byte

//go:embed electrolize/Electrolize-Regular.ttf
var Electrolize_Regular_ttf []byte

//go:embed pressstart2p/PressStart2P-Regular.ttf
var PressStart2P_Regular_ttf []byte

//go:embed ubuntu/Ubuntu-Medium.ttf
var Ubuntu_Medium_ttf []byte

//go:embed ubuntu/Ubuntu-LightItalic.ttf
var Ubuntu_LightItalic_ttf []byte

//go:embed ubuntu/Ubuntu-Regular.ttf
var Ubuntu_Regular_ttf []byte

//go:embed ubuntu/Ubuntu-Bold.ttf
var Ubuntu_Bold_ttf []byte

//go:embed ubuntu/Ubuntu-MediumItalic.ttf
var Ubuntu_MediumItalic_ttf []byte

//go:embed ubuntu/Ubuntu-BoldItalic.ttf
var Ubuntu_BoldItalic_ttf []byte

//go:embed ubuntu/Ubuntu-Italic.ttf
var Ubuntu_Italic_ttf []byte

//go:embed ubuntu/Ubuntu-Light.ttf
var Ubuntu_Light_ttf []byte
